### ISSUE TITLE
NAVpay doesn't work on GT-N7100

### ISSUE THREAD

**Issue by etch1** [Encrypt-S/NavPay#136]
Just a softlocked NAV logo when I start the app

Phone: GT-N7100
Android Version: 4.4.2
Latest app version

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-02-28T21:00:00+13:00","ped":"2018-03-03T09:00:00+13:00"})

**Comment by proletesseract** [comment]
This android version is not supported sorry.
