### ISSUE TITLE
NavPay 4.1.0 - Release testing

### ISSUE THREAD

**Issue by ro-savage** [Encrypt-S/NavPay#163]
# Release testing

##  Desktop Web
- [ ] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [ ] Import a backed up wallet (QR code)
- [ ] Export a backed up wallet (QR code)
- [ ] scanning wallet QR code
- [ ] scanning wallet QR code with amount
- [ ] See wallet balances in send page
- [ ] Send payment from wallet 1
- [ ] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypto
- [ ] Purchase Nav with Credit card

## Mobile Web (Use iOS)
- [x] Encrypt wallet with password
- [x] Refuse wallet encryption
- [x] Import a backed up wallet (QR code)
- [x] Export a backed up wallet (QR code)
- [x] scanning wallet QR code
- [x] scanning wallet QR code with amount
- [x] See wallet balances in send page
- [x] Send payment from wallet 1
- [x] Send payment from wallet 2
- [x] Send Private payment without NavTech
- [x] Add NavTech from send page
- [x] Delete NavTech from settings page
- [x] Add NavTech from settings page
- [x] Send NavTech private payment
- [x] Purchase Nav with Crypto
- [x] Purchase Nav with Credit card

## iOS PWA
- [ ] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [ ] Import a backed up wallet (QR code)
- [ ] Export a backed up wallet (QR code)
- [ ] scanning wallet QR code
- [ ] scanning wallet QR code with amount
- [ ] See wallet balances in send page
- [ ] Send payment from wallet 1
- [ ] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypto
- [ ] Purchase Nav with Credit card

## Android
- [x] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [x] Import a backed up wallet (QR code)
- [x] Export a backed up wallet (QR code)
- [ ] scanning wallet QR code
- [ ] scanning wallet QR code with amount
- [x] See wallet balances in send page
- [x] Send payment from wallet 1
- [x] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypot
- [ ] Purchase Nav with Credit card

## Desktop Mac
- [x] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [x] Import a backed up wallet (QR code)
- [ ] Export a backed up wallet (QR code)
- [x] scanning wallet QR code
- [x] scanning wallet QR code with amount
- [x] See wallet balances in send page
- [x] Send payment from wallet 1
- [ ] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypto
- [ ] Purchase Nav with Credit card

## Desktop Linux
- [ ] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [ ] Import a backed up wallet (QR code)
- [ ] Export a backed up wallet (QR code)
- [ ] scanning wallet QR code
- [ ] scanning wallet QR code with amount
- [ ] See wallet balances in send page
- [ ] Send payment from wallet 1
- [ ] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypto
- [ ] Purchase Nav with Credit card

## Desktop Windows
- [ ] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [ ] Import a backed up wallet (QR code)
- [ ] Export a backed up wallet (QR code)
- [ ] scanning wallet QR code
- [ ] scanning wallet QR code with amount
- [ ] See wallet balances in send page
- [ ] Send payment from wallet 1
- [ ] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypto
- [ ] Purchase Nav with Credit card

**Comment by matt-auckland** [comment]
## iOS
- [ ] Encrypt wallet with password
- [ ] Refuse wallet encryption
- [ ] Import a backed up wallet (QR code)
- [ ] Export a backed up wallet (QR code)
- [ ] scanning wallet QR code
- [ ] scanning wallet QR code with amount
- [ ] See wallet balances in send page
- [ ] Send payment from wallet 1
- [ ] Send payment from wallet 2
- [ ] Send Private payment without NavTech
- [ ] Add NavTech from send page
- [ ] Delete NavTech from settings page
- [ ] Add NavTech from settings page
- [ ] Send NavTech private payment
- [ ] Purchase Nav with Crypto
- [ ] Purchase Nav with Credit card
