### ISSUE TITLE
Receive Wallet Address

### ISSUE THREAD

**Issue by Cryptogail** [Encrypt-S/NavPay#165]
So I attempted to download the NavCoin core wallet however even with removing firewall, bootstrapping etc etc, I cant get past the 16week mark.  So I had sent some NAV from my binance account to the address it had generated.  Of course I cant receive the Navcoin sent now because the wallet wont download all the blocks.  So I now have set up a Navpay wallet and want to insert the receiving address so I can get the Navcoin that is sitting waiting to be collected.  Please assist.  Thankyou

**Comment by proletesseract** [comment]
you need to export the private key for the address from navcoin core and in navpay go to`settings > advanced > sweep private key` and enter the private key to move the funds to navpay.

GitHub issues are not the correct place for this type of technical support, it would recommend joining discord for any future user issues like this.

https://discord.gg/y4Vu9jw
