### ISSUE TITLE
nav electrum wallet not sending funds

### ISSUE THREAD

**Issue by nav2jj135** [Encrypt-S/NavPay#166]
it says: broadcasting...
 and then :  error server did not answer

Can someone please help.   It also says:  "Not connected" in the bottom left of the electrum wallet.
If i click on preferences the wallet closes I don't know how to export the private keys from here.

Can someone please help me.

**Comment by IfaqYurmama** [comment]
You can follow this tutorial to export private keys: https://info.navcoin.org/knowledge-base/how-do-i-get-coins-out-of-the-electrum-wallet/

**Comment by proletesseract** [comment]
NavPay is not NavCoin Electurm. Closing

**Comment by mxaddict** [comment]
We have an electrum wallet?

**Comment by IfaqYurmama** [comment]
We used to. It's no longer supported

Barry Deeney <notifications@github.com> schrieb am So., 30. Juni 2019,
10:03:

**Comment by mxaddict** [comment]
I see
