### ISSUE TITLE
Funds sent from NavPay - taken from balance but not showing in block explorer

### ISSUE THREAD

**Issue by kociiide** [Encrypt-S/NavPay#171]
Hi there,

I recently sent (about 8 hours ago) 2008NAV from my Navpay android app to my address at Binance like i have done many times. The problem is that the TX id is not apprearing on the block explorer even though the amount has been deducted from my balance on NavPay.

The transaction ID generated by Navpay is:
2930d3b7521ebbe06b0d859d37a565fa2acb39c820f8b23340dfecd15384663c

After checking the sent from address the NAV are still in my address and have not been sent! I then tried to send a small amount from binance to my Navpay address but that is not showing up either. My address is below:

NhA8XgGGnnED5GJwS1wdd2MWnuZyAHUYxL

Please help!

**Comment by proletesseract** [comment]
this address shows with 0 balance so i assume the issue is resolved and you were able to spend the coins eventually.
