### ISSUE TITLE
German Translation Issues

### ISSUE THREAD

**Issue by matt-auckland** [Encrypt-S/NavPay#61]
**German translations**

_Not translated:_

•	Settings -> Wallet -> Advanced -> Wallet Adresses: Explanation string not translated
•	Receive: Request specific amount string not translated
•	Receive: Generate new adress not translated
•	Send: Search or enter NavCoin adress not translated
•	Send: Private Payment -> Private Transaktion
•	Settings -> Wallet -> Advanced -> Wallet Service URL: Explanation string not translated
•	Home -> Recent Transactions -> Transaction -> Fee: x % of the transaction should be x% der Transaktion
•	Home -> Recent Transactions -> Transaction -> Fee -> View on blockchain: Title of popup window not translated, open cryptoID not translated

_Not ideal:_

•	Personal Wallet should be Translated as Persönliche Wallet not Persönliches Wallet
•	Settings -> Wallet -> Guthaben Verstecken should be Guthaben verstecken (lowercase v)
•	Settings -> Wallet -> Sicherung should stay Backup, Sicherung usually means fuse box
•	Settings -> Wallet -> Berechtigungscode abfragen should be Passwort or Passphrase
•	Settings -> Wallet -> Advance -> Public key should stay public key
•	Settings -> Advanced -> Unbestätigte Mittel einsetzen should be Unbestätigtes Guthaben einsetzen, Vermögen in the explanation text should also be changed to Guthaben
•	Settings -> Advanced -> Kürzlich Ausgeführte Transaktionen Karte makes no sense at all, should either be Kürzliche Transaktionen anzeigen or „Kürzliche Transaktionen“-Widget anzeigen
•	Settings -> Advanced -> Nächste Schritte Karte Anzeigen should be Tutorials anzeigen or Tutorials-Widget anzeigen
•	Home -> Recent Transactions -> Keine aktuellen Transaktionen should be keine kürzlichen Transaktionen

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-24T18:00:00+13:00","ped":"2017-11-24T19:30:00+13:00"})

**Comment by IfaqYurmama** [comment]
To add to this:

https://imgur.com/a/PHHbQ

In the changelly widget on the homescreen it still says "Kaufe Bitcoins"

Under contacts when you have none the string should say "Fügen Sie einen Kontakt hinzu"

Share NavPay should be "NayPay teilen" and the string on the sharing screen would be better like this: "Teilen Sie NavPay mit Ihren Freunden"


And under Settings it says "Fingerprint" under App Lock where it should say "Fingerabdruck"

**Comment by matt-auckland** [comment]
@IfaqYurmama I've updated some of these strings, but I some of your descriptions leave a bit of room for interpretation (I'm not sure if I should be replacing specific sentences or just single words in some cases, or which sentence on the page needs to be changed).

If you could do a format more like "Wrong translation" -> "Right translation" I can be sure I'm getting everything right.
